### ISSUE TITLE
README.md?

### ISSUE THREAD

**Issue by bmack** [pixelant/transliterator#1]
Hey team,

how about adding a README.md to understand what this extension does and when people should use it? This would be super cool!

Thanks!

**Comment by mabolek** [comment]
@bmack Thanks. I created a little README file now. Enjoy.

**Comment by bmack** [comment]
🙇

**Comment by christophlehmann** [comment]
IMHO you could replace the word "dirty" with "missing feature" in your readme :-) Would be nice to see this form of transliteration in the core.

**Comment by mabolek** [comment]
> IMHO you could replace the word "dirty" with "missing feature" in your readme :-) Would be nice to see this form of transliteration in the core.

Let's call it a proof of concept. "Somewhat dirty" refers less to the concept and more to the implementation. It subclasses in a way that I would avoid in production and it barely scratches the surface of `CharsetConverter`, which should probably be looked at in much more detail in order to supply a good solution. 😃
